import { Pinecone } from "@pinecone-database/pinecone";
import OpenAI from "openai";
import * as dotenv from "dotenv";
import * as path from "path";
dotenv.config({ path: path.resolve(process.cwd(), ".env.local") });

const openai = new OpenAI({ apiKey: process.env.OPENAI_API_KEY });
const pc = new Pinecone({ apiKey: process.env.PINECONE_API_KEY! });

const wisdom = [
  { id: "wisdom-universal-001", text: "In the first 72 hours after a cancer diagnosis, most caregivers make the same mistake: they go into logistics mode immediately before they have allowed themselves to feel anything. This creates emotional suppression that compounds over months. The most important thing a caregiver can do in the first 24 hours is not research. It is to sit with the person who was diagnosed and say nothing. Just be present. The logistics will still be there tomorrow. The window for real human connection closes faster than people expect.", metadata: { cancerType: "universal", topic: "first_72_hours" } },
  { id: "wisdom-universal-002", text: "Caregivers universally underestimate how much they will need to advocate inside the healthcare system. Doctors are overloaded. Nurses are stretched. Schedulers make mistakes. The caregiver who gets the best outcomes is the one who learns to be politely relentless — calling back the same day if they do not hear, asking the nurse navigator directly, showing up in person when phone calls are not returned. The system rewards persistence, not patience.", metadata: { cancerType: "universal", topic: "advocacy" } },
  { id: "wisdom-universal-003", text: "The single most common financial mistake caregivers make is not calling the hospital financial counselor within the first week. Every major cancer center has one. They can set up payment plans, apply for charity care, connect the family with disease-specific foundations, and flag billing errors — which occur in over 80% of hospital bills. Most families do not know this person exists until they are already drowning in debt. Ask for the financial counselor on day one.", metadata: { cancerType: "universal", topic: "financial" } },
  { id: "wisdom-universal-004", text: "Second opinions are not disloyal. They are standard of care. The National Cancer Institute recommends second opinions for all cancer diagnoses. Most oncologists expect and support them. The window matters: get the second opinion before treatment begins, not after. A second opinion at an NCI-designated Comprehensive Cancer Center can change the treatment plan in 15-30% of cases and costs the same as a first opinion under most insurance plans.", metadata: { cancerType: "universal", topic: "second_opinion" } },
  { id: "wisdom-universal-005", text: "Caregiver burnout follows a predictable pattern. Phase 1 is hypervigilance — doing everything, sleeping little, feeling needed. Phase 2 is exhaustion — still doing everything but running on empty, irritable, making mistakes. Phase 3 is collapse. The transition from Phase 1 to Phase 2 typically happens between weeks 4 and 8. Building in respite before Phase 2 begins is the only reliable prevention. Ask your social worker about respite care resources on week 2, not week 8.", metadata: { cancerType: "universal", topic: "caregiver_burnout" } },
  { id: "wisdom-universal-006", text: "The hardest conversations are not with the medical team — they are with your own family. The person who lives closest takes on the most. The sibling who lives far away questions decisions from a distance without bearing the daily weight. A single session with a social worker or family therapist in the first month — not because anything is wrong, but as prevention — is one of the highest-leverage investments a family can make.", metadata: { cancerType: "universal", topic: "family_dynamics" } },
  { id: "wisdom-universal-007", text: "Keep a medical notebook from day one. Write down every doctor's name, specialty, and direct phone number. Write down every test ordered and when results are expected. Write down every medication and dose. Write down every question you think of, even at 2am. Bring this notebook to every appointment. Ask the doctor to speak slowly enough for you to write. This single habit prevents more medical errors and communication failures than any app or system.", metadata: { cancerType: "universal", topic: "organization" } },
  { id: "wisdom-universal-008", text: "The emotional experience of being a cancer caregiver includes feelings most people are ashamed to admit: resentment, anger at the person who is sick, relief when a hard day ends, fear of being abandoned if the person dies. These feelings are normal, documented, and do not make someone a bad caregiver. They make someone human. The caregiver who cannot acknowledge these feelings carries a weight that eventually breaks them. ASCO Psycho-Oncology guidelines specifically address caregiver emotional health as part of standard of care.", metadata: { cancerType: "universal", topic: "caregiver_emotions" } },
  { id: "wisdom-colon-001", text: "The most important thing a colon cancer caregiver must do in the first week is ensure the complete pathology report is in their hands — not a summary, not a verbal explanation, the full written report. This report contains T stage, N stage, M stage, tumor grade, lymphovascular invasion status, perineural invasion status, and margin status. Each factor directly affects treatment decisions. Request it from the pathology department directly, not just from the surgeon.", metadata: { cancerType: "colon", topic: "pathology_report" } },
  { id: "wisdom-colon-002", text: "For colon cancer, MMR and MSI testing is standard of care per NCCN guidelines and must be done on the tumor tissue at the time of surgery. MSI-High status changes the treatment plan significantly — MSI-H patients may not benefit from certain chemotherapy regimens and may be candidates for immunotherapy instead. Many community hospitals do not automatically order this test. Ask explicitly: Has MMR and MSI testing been ordered on the tumor tissue?", metadata: { cancerType: "colon", topic: "msi_testing" } },
  { id: "wisdom-colon-003", text: "Full recovery from colon resection surgery takes 4-6 weeks. During this period the patient cannot drive, should not lift more than 10 pounds, needs wound monitoring, and may experience significant fatigue and bowel changes. Many caregivers return to work too early. Identify who will provide daytime coverage during the first 4 weeks before surgery, not after. This logistics cannot be improvised.", metadata: { cancerType: "colon", topic: "surgical_recovery" } },
  { id: "wisdom-colon-004", text: "For Stage III colon cancer, adjuvant chemotherapy — typically FOLFOX or CAPOX — is standard of care and usually begins 4-8 weeks after surgery. If the gap between surgery and chemotherapy exceeds 8 weeks, outcomes worsen significantly. Caregivers must proactively schedule the medical oncology consultation before the surgery date. The surgical team and medical oncologist are often different doctors who do not automatically coordinate. The caregiver must bridge this gap.", metadata: { cancerType: "colon", topic: "adjuvant_chemo" } },
  { id: "wisdom-colon-005", text: "Lynch syndrome — a hereditary condition causing colon cancer — is present in approximately 3-5% of all colon cancer cases. If identified, first-degree relatives need immediate screening. If not identified, those relatives may develop preventable cancers. Ask: Should we see a genetic counselor? The answer for early-onset colon cancer under age 50 or with family history should almost always be yes.", metadata: { cancerType: "colon", topic: "genetics" } },
  { id: "wisdom-colon-006", text: "Ostomy nurses — Wound, Ostomy and Continence nurses — are essential to recovery when colostomy or ileostomy is created during colon surgery. The learning curve for stoma care is steep and emotionally difficult. Request a WOC nurse consultation before surgery, not after. Starting the education before surgery dramatically improves adjustment and outcomes.", metadata: { cancerType: "colon", topic: "ostomy_care" } },
  { id: "wisdom-breast-001", text: "Breast cancer caregivers are frequently overwhelmed by the number of specialists involved: surgical oncologist, medical oncologist, radiation oncologist, plastic surgeon, and sometimes a fertility specialist. These specialists do not always communicate automatically. The caregiver's most important job in the first two weeks is to understand who is on the team, in what order decisions need to be made, and who is coordinating the overall plan. Ask explicitly: Who is our primary point of contact for the overall treatment plan?", metadata: { cancerType: "breast", topic: "care_coordination" } },
  { id: "wisdom-breast-002", text: "For premenopausal women with hormone receptor-positive breast cancer, fertility preservation is a time-sensitive decision that must be addressed before chemotherapy begins. The window to harvest eggs or embryos is typically 2-4 weeks and must happen before the first chemo cycle. Many oncology teams do not proactively raise this. The caregiver must ask: Should we see a reproductive endocrinologist before starting chemotherapy? This question cannot be asked after treatment begins.", metadata: { cancerType: "breast", topic: "fertility_preservation" } },
  { id: "wisdom-breast-003", text: "For early-stage breast cancer, survival outcomes are equivalent between lumpectomy and mastectomy when combined with appropriate radiation. However mastectomy has higher complication rates, longer recovery, and significant psychological impact. Many patients choose mastectomy believing it is safer when the data does not support this. Ensure the patient hears from both a surgical oncologist and a breast cancer specialist before making this decision.", metadata: { cancerType: "breast", topic: "surgical_decision" } },
  { id: "wisdom-breast-004", text: "BRCA1 and BRCA2 genetic testing is recommended for all patients with breast cancer under age 50, triple-negative breast cancer at any age, Ashkenazi Jewish heritage, or family history of breast, ovarian, or pancreatic cancer. If a BRCA mutation is found it has implications for every first-degree relative. Ask the oncologist at the first appointment: Does she qualify for genetic testing?", metadata: { cancerType: "breast", topic: "brca_testing" } },
  { id: "wisdom-breast-005", text: "Cold cap therapy can reduce chemotherapy-related hair loss by 50-60% for some breast cancer patients and is FDA-cleared. It must be arranged before the first infusion. Not all cancer centers offer it but many do. Ask the chemotherapy nurse coordinator before the first treatment date: Do you offer cold cap therapy? This cannot be retroactively applied.", metadata: { cancerType: "breast", topic: "cold_cap" } },
  { id: "wisdom-breast-006", text: "Breast cancer active treatment can span 18-24 months when surgery, chemotherapy, radiation, and targeted therapy such as Herceptin for HER2-positive disease are combined. The caregiver who plans for a 6-month sprint and faces another year is at high risk for burnout. Ask the oncologist at the start: What does the complete treatment timeline look like from today through the end of active treatment? Get the full picture before making career or financial decisions.", metadata: { cancerType: "breast", topic: "treatment_duration" } },
  { id: "wisdom-lymphoma-001", text: "Lymphoma is not one disease — it contains over 70 distinct subtypes each with different biology, treatment, and prognosis. A caregiver who does not know the exact subtype cannot effectively research, advocate, or ask the right questions. The first question at every appointment should be: What is the exact subtype of lymphoma, and how does that affect the treatment approach?", metadata: { cancerType: "lymphoma", topic: "subtype" } },
  { id: "wisdom-lymphoma-002", text: "For lymphoma, a mid-treatment PET-CT scan after 2 cycles of chemotherapy — called an interim PET — directly determines whether treatment continues unchanged, is intensified, or is switched entirely. Before treatment starts ask: When will we do the interim PET, and what will we do differently based on the result? Most caregivers do not realize this scan is happening or what it means.", metadata: { cancerType: "lymphoma", topic: "interim_pet" } },
  { id: "wisdom-lymphoma-003", text: "For lymphoma patients who have received certain radiation or are immunocompromised, irradiated blood products are required to prevent transfusion-associated graft-versus-host disease — a rare but fatal complication. Not all hospitals automatically provide irradiated blood. Ask the treatment team: Does my loved one need irradiated blood products, and has this been flagged in the blood bank order?", metadata: { cancerType: "lymphoma", topic: "irradiated_blood" } },
  { id: "wisdom-lymphoma-004", text: "Insurers deny one in four initial requests for blood cancer medications per ASH 2024 data. The appeal process takes days to weeks, and during active lymphoma treatment a delay of even 7-10 days can affect outcomes. Call the insurance company the day the treatment is prescribed — not when the denial arrives — and ask: Has prior authorization been submitted, and what is the expected timeline?", metadata: { cancerType: "lymphoma", topic: "insurance" } },
  { id: "wisdom-lymphoma-005", text: "For aggressive or rare lymphoma subtypes, NCI-designated Cancer Centers with dedicated lymphoma programs have access to clinical trials and subspecialists who see lymphoma exclusively. For aggressive lymphomas, rare subtypes, relapsed disease, or any case where the path forward is unclear, a consultation at an NCI-designated center should happen before treatment begins — not after first-line therapy fails.", metadata: { cancerType: "lymphoma", topic: "treatment_center" } },
  { id: "wisdom-lymphoma-006", text: "Clinical trials for lymphoma often offer access to newer agents not yet standard of care but showing superior response rates. The time to ask is before first-line treatment begins, not after relapse. Ask the oncologist at the first treatment planning appointment: Are there any clinical trials we should consider before starting standard chemotherapy?", metadata: { cancerType: "lymphoma", topic: "clinical_trials" } },
  { id: "wisdom-lymphoma-007", text: "Neutropenic fever — a fever above 100.4F in a patient with low white blood cell counts from chemotherapy — is a medical emergency requiring immediate ER evaluation, not a wait-and-see approach. Many caregivers wait hours before going in. The chemotherapy team must explicitly teach the caregiver what temperature requires an ER visit, when to call the on-call oncologist first, and which ER is preferred.", metadata: { cancerType: "lymphoma", topic: "neutropenic_fever" } },
];

async function embedAndUpsert() {
  const index = pc.index(process.env.PINECONE_INDEX_NAME!).namespace("wisdom");
  console.log(`Upserting ${wisdom.length} wisdom chunks...`);
  for (const chunk of wisdom) {
    const res = await openai.embeddings.create({ model: "text-embedding-3-small", input: chunk.text });
    await index.upsert({ records: [{ id: chunk.id, values: res.data[0].embedding, metadata: { ...chunk.metadata, text: chunk.text } }] });
    console.log(`✅ ${chunk.id}`);
  }
  console.log("Done.");
}
embedAndUpsert().catch(console.error);
